/// @license Propriety <http://license.url>
/// @copyright Copyright (C) Turbo Labz 2017 - All rights reserved
/// Unauthorized copying of this file, via any medium is strictly prohibited
/// Proprietary and confidential
/// 
/// @author Faraz Ahmed <faraz@turbolabz.com>
/// @company Turbo Labz <http://turbolabz.com>
/// @date 2017-03-24 10:45:49 UTC+05:00
/// 
/// @description
/// [add_description_here]
using System.Collections.Generic;
using UnityEngine;

namespace TurboLabz.TLUtils
{
    public static class Flags
    {

        static Dictionary<string, string> countryList = new Dictionary<string, string> {
            {"AD", "Andorra"},
            {"AE", "Unknown" },
            {"AF", "Afghanistan"},
            {"AG", "Antigua and Barbuda"},
            {"AI", "Anguilla"},
            {"AL", "Albania"},
            {"AM", "Armenia"},
            {"AO", "Angola"},
            {"AQ", "Antarctica"},
            {"AR", "Argentina"},
            {"AS", "American Samoa"},
            {"AT", "Austria"},
            {"AU", "Australia"},
            {"AW", "Aruba"},
            {"AX", "Aland Islands"},
            {"AZ", "Azerbaijan"},
            {"BA", "Bosnia and Herzegovina"},
            {"BB", "Barbados"},
            {"BD", "Bangladesh"},
            {"BE", "Belgium"},
            {"BF", "Burkina Faso"},
            {"BG", "Bulgaria"},
            {"BM", "Bermuda"},
            {"BN", "Brunei Darussalam"},
            {"BO", "Bolivia(Plurinational State of)"},
            {"BQ", "Bonaire, Sint Eustatius and Saba"},
            {"BR", "Brazil"},
            {"BS", "Bahamas"},
            {"BT", "Bhutan"},
            {"BV", "Bouvet Island"},
            {"BW", "Botswana"},
            {"BY", "Belarus"},
            {"BZ", "Belize"},
            {"CA", "Canada"},
            {"CC", "Cocos(Keeling) Islands"},
            {"CD", "Congo(the Democratic Republic of the)"},
            {"CF", "Central African Republic(the)"},
            {"CG", "Congo(the)"},
            {"CH", "Switzerland"},
            {"CI", "Cote d'Ivoire"},
            {"CK", "Cook Islands(the)"},
            {"CL", "Chile"},
            {"CM", "Cameroon"},
            {"CN", "China"},
            {"CO", "Colombia"},
            {"CR", "Costa Rica"},
            {"CU", "Cuba"},
            {"CV", "Cabo Verde"},
            {"CW", "Curacao"},
            {"CX", "Christmas Island"},
            {"CY", "Cyprus"},
            {"CZ", "Czech Republic(the)"},
            {"DE", "Unknown"},
            {"DJ", "Djibouti"},
            {"DK", "Denmark"},
            {"DM", "Dominica"},
            {"DO", "Dominican Republic(the)"},
            {"DZ", "Algeria"},
            {"EC", "Ecuador"},
            {"EE", "Estonia"},
            {"EG", "Egypt"},
            {"EH", "Unknown"},
            {"ER", "Eritrea"},
            {"ES", "Unknown"},
            {"ET", "Ethiopia"},
            {"FI", "Finland"},
            {"FJ", "Fiji"},
            {"FK", "Falkland Islands(the) [Malvinas]"},
            {"FM", "Unknown"},
            {"FO", "Faroe Islands(the)"},
            {"FR", "France"},
            {"GA", "Gabon"},
            {"GB", "Unknown"},
            {"GD", "Grenada"},
            {"GE", "Georgia"},
            {"GF", "French Guiana"},
            {"GG", "Guernsey"},
            {"GH", "Ghana"},
            {"GI", "Gibraltar"},
            {"GL", "Greenland"},
            {"GM", "Gambia(the)"},
            {"GN", "Guinea"},
            {"GP", "Guadeloupe"},
            {"GQ", "Equatorial Guinea"},
            {"GR", "Greece"},
            {"GS", "Unknown"},
            {"GT", "Guatemala"},
            {"GU", "Guam"},
            {"GW", "Guinea-Bissau"},
            {"GY", "Guyana"},
            {"HK", "Hong Kong"},
            {"HM", "Heard Island and McDonald Islands"},
            {"HN", "Honduras"},
            {"HR", "Croatia"},
            {"HT", "Haiti"},
            {"HU", "Hungary"},
            {"ID", "Indonesia"},
            {"IE", "Ireland"},
            {"IL", "Israel"},
            {"IM", "Isle of Man"},
            {"IN", "India"},
            {"IO", "British Indian Ocean Territory(the)"},
            {"IQ", "Iraq"},
            {"IR", "Iran(Islamic Republic of)"},
            {"IS", "Iceland"},
            {"IT", "Italy"},
            {"JE", "Jersey"},
            {"JM", "Jamaica"},
            {"JO", "Jordan"},
            {"JP", "Japan"},
            {"KE", "Kenya"},
            {"KG", "Kyrgyzstan"},
            {"KH", "Cambodia"},
            {"KI", "Kiribati"},
            {"KM", "Comoros(the)"},
            {"KN", "Unknown"},
            {"KP", "Korea(the Democratic People's Republic of)"},
            {"KR", "Korea (the Republic of)"},
            {"KW", "Kuwait"},
            {"KY", "Unknown"},
            {"KZ", "Kazakhstan"},
            {"LA", "Lao People's Democratic Republic (the)"},
            {"LB", "Lebanon"},
            {"LC", "Saint Lucia"},
            {"LI", "Liechtenstein"},
            {"LK", "Sri Lanka"},
            {"LR", "Liberia"},
            {"LS", "Lesotho"},
            {"LT", "Lithuania"},
            {"LU", "Luxembourg"},
            {"LV", "Latvia"},
            {"LY", "Libya"},
            {"MA", "Morocco"},
            {"MC", "Monaco"},
            {"MD", "Moldova(the Republic of)"},
            {"ME", "Montenegro"},
            {"MF", "Unknown"},
            {"MG", "Madagascar"},
            {"MH", "Marshall Islands(the)"},
            {"MK", "Macedonia(the former Yugoslav Republic of)"},
            {"ML", "Mali"},
            {"MM", "Myanmar"},
            {"MN", "Mongolia"},
            {"MO", "Macao"},
            {"MP", "Northern Mariana Islands(the)"},
            {"MQ", "Martinique"},
            {"MR", "Mauritania"},
            {"MS", "Montserrat"},
            {"MT", "Malta"},
            {"MU", "Mauritius"},
            {"MV", "Maldives"},
            {"MW", "Malawi"},
            {"MX", "Mexico"},
            {"MY", "Malaysia"},
            {"MZ", "Mozambique"},
            {"NA", "Namibia"},
            {"NC", "New Caledonia"},
            {"NE", "Niger(the)"},
            {"NF", "Norfolk Island"},
            {"NG", "Nigeria"},
            {"NI", "Nicaragua"},
            {"NL", "Netherlands(the)"},
            {"NO", "Norway"},
            {"NP", "Nepal"},
            {"NR", "Nauru"},
            {"NU", "Niue"},
            {"NZ", "New Zealand"},
            {"OM", "Oman"},
            {"PA", "Panama"},
            {"PE", "Peru"},
            {"PF", "Unknown"},
            {"PG", "Papua New Guinea"},
            {"PH", "Philippines(the)"},
            {"PK", "Pakistan"},
            {"PL", "Poland"},
            {"PM", "Saint Pierre and Miquelon"},
            {"PN", "Pitcairn"},
            {"PR", "Puerto Rico"},
            {"PS", "Palestine, State of"},
            {"PT", "Portugal"},
            {"PW", "Palau"},
            {"PY", "Paraguay"},
            {"QA", "Qatar"},
            {"RE", "Réunion"},
            {"RO", "Romania"},
            {"RS", "Serbia"},
            {"RU", "Russian Federation(the)"},
            {"RW", "Rwanda"},
            {"SA", "Saudi Arabia"},
            {"SB", "Solomon Islands"},
            {"SC", "Seychelles"},
            {"SD", "Sudan(the)"},
            {"SE", "Sweden"},
            {"SG", "Singapore"},
            {"SH", "Saint Helena, Ascension and Tristan da Cunha"},
            {"SI", "Slovenia"},
            {"SJ", "Svalbard and Jan Mayen"},
            {"SK", "Slovakia"},
            {"SL", "Sierra Leone"},
            {"SM", "San Marino"},
            {"SN", "Senegal"},
            {"SO", "Somalia"},
            {"SR", "Suriname"},
            {"SS", "South Sudan"},
            {"ST", "Sao Tome and Principe"},
            {"SV", "Unknown"},
            {"SX", "Sint Maarten(Dutch part)"},
            {"SY", "Syrian Arab Republic"},
            {"SZ", "Swaziland"},
            {"TC", "Turks and Caicos Islands(the)"},
            {"TD", "Unknown"},
            {"TF", "Unknown"},
            {"TG", "Togo"},
            {"TH", "Thailand"},
            {"TJ", "Tajikistan"},
            {"TK", "Tokelau"},
            {"TL", "Timor-Leste"},
            {"TM", "Turkmenistan"},
            {"TN", "Tunisia"},
            {"TO", "Tonga"},
            {"TR", "Turkey"},
            {"TT", "Trinidad and Tobago"},
            {"TV", "Tuvalu"},
            {"TW", "Taiwan(Province of China)"},
            {"TZ", "Tanzania, United Republic of"},
            {"UA", "Ukraine"},
            {"UG", "Uganda"},
            {"UM", "United States Minor Outlying Islands(the)"},
            {"US", "United States of America(the)"},
            {"UY", "Uruguay"},
            {"UZ", "Uzbekistan"},
            {"VA", "Unknown"},
            {"VC", "Unknown"},
            {"VE", "Venezuela(Bolivarian Republic of)"},
            {"VG", "Virgin Islands(British)"},
            {"VI", "Virgin Islands(U.S.)"},
            {"VN", "Viet Nam"},
            {"VU", "Vanuatu"},
            {"WF", "Wallis and Futuna"},
            {"WS", "Unknown"},
            {"YE", "Yemen"},
            {"YT", "Unknown"},
            {"ZA", "Unknown"},
            {"ZM", "Zambia"},
            {"ZW", "Zimbabwe"}

            };


        public static Sprite GetFlag(string countryId)
        {
            Sprite flag = null;

            if (countryId != null)
            {
                flag = Resources.Load<Sprite>("Flags/" + countryId);
            }

            if (flag == null)
            {
                flag = Resources.Load<Sprite>("Flags/_Unknown");
            }

            return flag;
        }

        public static string GetCountry(string countryCode)
        {
            if (countryList.ContainsKey(countryCode))
            {
                return countryList[countryCode];
            }

            return "Unknown";
        }
    }
}
