/// @license Propriety <http://license.url>
/// @copyright Copyright (C) Turbo Labz 2017 - All rights reserved
/// Unauthorized copying of this file, via any medium is strictly prohibited
/// Proprietary and confidential
/// 
/// @author Faraz Ahmed <faraz@turbolabz.com>
/// @company Turbo Labz <http://turbolabz.com>
/// @date 2017-02-11 15:26:26 UTC+05:00
/// 
/// @description
/// [add_description_here]

namespace TurboLabz.Chess
{
    public static class AiMoveTimes
    {
        public static float[][] M_1  = new float[][] {  new float[] { 1, 1.5f },  new float[] { 1, 1.5f },  new float[] { 1, 1.5f },  new float[] { 1, 1.5f },  new float[] { 1, 1.5f },  new float[] { 1, 1.5f },  new float[] { 1, 1.5f },  new float[] { 1, 1.5f },  new float[] { 1, 1.5f },  new float[] { 1, 1.5f },  new float[] { 1, 1.5f },  new float[] { 1, 1.5f },  new float[] { 1, 1.5f },  new float[] { 1, 1.5f },  new float[] { 1, 1.5f },  new float[] { 1, 2 },  new float[] { 1, 2 },  new float[] { 1, 2 },  new float[] { 1, 2 },  new float[] { 1, 2 },  new float[] { 1, 2 },  new float[] { 1, 2 },  new float[] { 1, 2 },  new float[] { 1, 1.5f },  new float[] { 1, 1.5f },  new float[] { 1, 1.5f },  new float[] { 1, 1.5f },  new float[] { 1, 1.5f },  new float[] { 1, 1.5f },  new float[] { 1, 1.5f },  new float[] { 1, 1.5f },  new float[] { 1, 1.5f },  new float[] { 1, 1.5f },  new float[] { 1, 1.5f },  new float[] { 1, 1.5f },  new float[] { 1, 1.5f },  new float[] { 1, 1.5f },  new float[] { 1, 1.5f },  new float[] { 1, 1.5f },  new float[] { 1, 1.5f },  new float[] { 1, 1.5f },  new float[] { 1, 1.5f },  new float[] { 1, 1.5f },  new float[] { 1, 1.5f },  new float[] { 1, 1.5f },  new float[] { 1, 1.5f },  new float[] { 1, 1.5f },  new float[] { 1, 1.5f },  new float[] { 1, 1.5f },  new float[] { 1, 1.5f },  new float[] { 1, 1.5f },  new float[] { 1, 1.5f },  new float[] { 1, 1.5f },  new float[] { 1, 1.5f },  new float[] { 1, 1.5f },  new float[] { 1, 1.5f },  new float[] { 1, 1.5f },  new float[] { 1, 1.5f } };
        public static float[][] M_3  = new float[][] {  new float[] { 1, 2 },  new float[] { 1, 2 },  new float[] { 1, 3 },  new float[] { 1, 3 },  new float[] { 1, 3 },  new float[] { 1, 5 },  new float[] { 1, 5 },  new float[] { 1, 5 },  new float[] { 1, 6 },  new float[] { 1, 6 },  new float[] { 1, 7 },  new float[] { 1, 8 },  new float[] { 1, 8 },  new float[] { 1, 7 },  new float[] { 1, 9 },  new float[] { 1, 9 },  new float[] { 1, 9 },  new float[] { 1, 9 },  new float[] { 1, 9 },  new float[] { 1, 9 },  new float[] { 1, 9 },  new float[] { 1, 9 },  new float[] { 1, 9 },  new float[] { 1, 9 },  new float[] { 1, 7 },  new float[] { 1, 7 },  new float[] { 1, 7 },  new float[] { 1, 7 },  new float[] { 1, 7 },  new float[] { 1, 7 },  new float[] { 1, 6 },  new float[] { 1, 5 },  new float[] { 1, 5 },  new float[] { 1, 5 },  new float[] { 1, 5 },  new float[] { 1, 4 },  new float[] { 1, 4 },  new float[] { 1, 4 },  new float[] { 1, 4 },  new float[] { 1, 4 },  new float[] { 1, 4 },  new float[] { 1, 4 },  new float[] { 1, 3 },  new float[] { 1, 2 },  new float[] { 1, 2 },  new float[] { 1, 3 },  new float[] { 1, 2 },  new float[] { 1, 2 },  new float[] { 1, 2 },  new float[] { 1, 2 },  new float[] { 1, 2 },  new float[] { 1, 2 },  new float[] { 1, 2 },  new float[] { 1, 2 },  new float[] { 1, 2 },  new float[] { 1, 2 },  new float[] { 1, 2 },  new float[] { 1, 2 }  };
        public static float[][] M_5  = new float[][] {  new float[] { 1, 3 },  new float[] { 1, 3 },  new float[] { 1, 3 },  new float[] { 1, 6 },  new float[] { 1, 6 },  new float[] { 1, 8 },  new float[] { 1, 8 },  new float[] { 1, 9 },  new float[] { 1, 9 },  new float[] { 1, 10 },  new float[] { 1, 11 },  new float[] { 1, 11 },  new float[] { 1, 12 },  new float[] { 1, 12 },  new float[] { 1, 12 },  new float[] { 1, 13 },  new float[] { 1, 13 },  new float[] { 1, 13 },  new float[] { 1, 13 },  new float[] { 1, 13 },  new float[] { 1, 13 },  new float[] { 1, 13 },  new float[] { 1, 12 },  new float[] { 1, 12 },  new float[] { 1, 12 },  new float[] { 1, 12 },  new float[] { 1, 12 },  new float[] { 1, 11 },  new float[] { 1, 10 },  new float[] { 1, 10 },  new float[] { 1, 10 },  new float[] { 1, 10 },  new float[] { 1, 9 },  new float[] { 1, 8 },  new float[] { 1, 8 },  new float[] { 1, 8 },  new float[] { 1, 7 },  new float[] { 1, 7 },  new float[] { 1, 7 },  new float[] { 1, 6 },  new float[] { 1, 6 },  new float[] { 1, 5 },  new float[] { 1, 5 },  new float[] { 1, 5 },  new float[] { 1, 5 },  new float[] { 1, 4 },  new float[] { 1, 4 },  new float[] { 1, 4 },  new float[] { 1, 4 },  new float[] { 1, 4 },  new float[] { 1, 4 },  new float[] { 1, 4 },  new float[] { 1, 4 },  new float[] { 1, 4 },  new float[] { 1, 3 },  new float[] { 1, 2 },  new float[] { 1, 2 },  new float[] { 1, 2 } };
        public static float[][] M_10 = new float[][] {  new float[] { 1, 3 },  new float[] { 1, 3 },  new float[] { 1, 3 },  new float[] { 1, 12 },  new float[] { 1, 12 },  new float[] { 1, 13 },  new float[] { 1, 15 },  new float[] { 1, 15 },  new float[] { 1, 17 },  new float[] { 1, 19 },  new float[] { 1, 19 },  new float[] { 1, 21 },  new float[] { 1, 21 },  new float[] { 1, 21 },  new float[] { 1, 21 },  new float[] { 1, 22 },  new float[] { 1, 21 },  new float[] { 1, 22 },  new float[] { 1, 21 },  new float[] { 1, 22 },  new float[] { 1, 21 },  new float[] { 1, 22 },  new float[] { 1, 22 },  new float[] { 1, 21 },  new float[] { 1, 22 },  new float[] { 1, 21 },  new float[] { 1, 20 },  new float[] { 1, 18 },  new float[] { 1, 18 },  new float[] { 1, 17 },  new float[] { 1, 17 },  new float[] { 1, 16 },  new float[] { 1, 16 },  new float[] { 1, 16 },  new float[] { 1, 15 },  new float[] { 1, 14 },  new float[] { 1, 13 },  new float[] { 1, 13 },  new float[] { 1, 13 },  new float[] { 1, 13 },  new float[] { 1, 12 },  new float[] { 1, 12 },  new float[] { 1, 11 },  new float[] { 1, 11 },  new float[] { 1, 10 },  new float[] { 1, 10 },  new float[] { 1, 10 },  new float[] { 1, 10 },  new float[] { 1, 8 },  new float[] { 1, 8 },  new float[] { 1, 8 },  new float[] { 1, 9 },  new float[] { 1, 8 },  new float[] { 1, 11 },  new float[] { 1, 7 },  new float[] { 1, 5 },  new float[] { 1, 5 },  new float[] { 1, 4 } };

        public const float M_CPU = 1f;
        public const float M_FAST = 0f;
        public const float M_SLOW = 5f;
    }
}
