using UnityEditor;

namespace HUFEXT.PackageManager.Editor.Commands.Processing
{
    // This command is for clearing all data generated by package manager.
    // It should remove auth token, all registry keys and data, close PM window.
    public class ClearPackageManagerDataCommand : Core.Command.Base
    {
        public override void Execute()
        {
            Models.Token.Invalidate();
            Core.Registry.Clear();
            Core.Registry.Push( Models.Keys.PACKAGE_MANAGER_FORCE_CLOSE );
            AssetDatabase.Refresh();
            Complete( true );
        }
    }
}